### ISSUE TITLE
能否添加一个http2+caddy+TLS的模板？

### ISSUE THREAD

**Issue by tufu9441** [KiriKira/vTemplate#11]
如题，v2ray最近的版本支持http2之后，不少人想尝试实现h2+caddy+TLS的搭配，不知能否添加这样的模板？

**Comment by KiriKira** [comment]
截至目前, http/2 尚未进入[官方文档](http://v2ray.com)中, 原因似乎是仍然有不完善的地方. 并且客户端对 http/2 的支持也不完全(我个人而言主要是等 BifrostV 更新), 因此暂时不考虑, 不过等官方文档中推出后我会去试试. 如果有人实验成功了欢迎直接pr.

**Comment by tufu9441** [comment]
原来如此，了解了，谢谢！
