### ISSUE TITLE
“TCP”配置意义是什么？

### ISSUE THREAD

**Issue by escapezn** [KiriKira/vTemplate#15]
在v2ray的官方文档传输配置一节里写到

> network: 数据流所使用的网络，可选的值为 "tcp"、 "kcp" 或 "ws"，默认值为 "tcp"；

这里的意思是不是v2ray默认的传输协议就是tcp？这样的话那么本站的TCP配置文件和单纯的vmess不就没有区别了吗？

**Comment by KiriKira** [comment]
是的，是一样的。只是当时看到 pull request 脑子一短路就点了确定了（
