### ISSUE TITLE
请问为什么要设置两个id

### ISSUE THREAD

**Issue by no-name2017** [KiriKira/vTemplate#17]
"clients": [
        {
          "id": "a90597c1-bab3-4217-ad6f-0838675c8633",
          "alterId": 10
        },
        {
          "id": "8856ea72-a67a-4651-98f0-ebb3bf4f07b1",
          "level": 1,
          "security": "aes-128-gcm",
          "alterId": 12
        }

新手不太懂，为什么vmess协议里，要设置两个id，请求解答，感谢。

**Comment by KiriKira** [comment]
仅作示例，你可以使用两个 id 来提供多用户。
